apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-prs
  annotations:
    milano.powerapp.cloud/stack.autoprovision.limit: "3"
  labels:
    powerapp.cloud/global-registry-access: "yes"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-template
  namespace: hello-world-prs
data:
  objects.yaml: |
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: developers-access
    subjects:
    - kind: Group
      name: appDevelopers
      apiGroup: rbac.authorization.k8s.io
    - kind: ServiceAccount
      name: milano
      namespace: milano-production
    roleRef:
      kind: ClusterRole
      name: global:developer
      apiGroup: rbac.authorization.k8s.io
    ---
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: compute-resources
    spec:
      hard:
        pods: "1000"
        requests.cpu: "10"
        requests.memory: "10Gi"
        requests.ephemeral-storage: "60Gi"
        limits.cpu: "20"
        limits.memory: "25Gi"
        limits.ephemeral-storage: "60Gi"
        configmaps: "1000"
        requests.storage: "30Gi"
        persistentvolumeclaims: "1000"
        replicationcontrollers: "1000"
        secrets: "1000"
        services: "1000"
        services.loadbalancers: "0"
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: percona-xtradb-cluster-operator
    ---
    kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: service-account-percona-xtradb-cluster-operator
    subjects:
    - kind: ServiceAccount
      name: percona-xtradb-cluster-operator
    roleRef:
      kind: ClusterRole
      name: percona-xtradb-cluster-operator
      apiGroup: rbac.authorization.k8s.io
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: percona-xtradb-cluster-operator
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: percona-xtradb-cluster-operator
      template:
        metadata:
          labels:
            name: percona-xtradb-cluster-operator
        spec:
          serviceAccountName: percona-xtradb-cluster-operator
          containers:
            - name: percona-xtradb-cluster-operator
              image: percona/percona-xtradb-cluster-operator:1.4.0
              ports:
              - containerPort: 60000
                name: metrics
                protocol: TCP
              command:
              - percona-xtradb-cluster-operator
              imagePullPolicy: Always
              env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAME
                  value: "percona-xtradb-cluster-operator"
              resources:
                requests:
                  cpu: "200m"
                  memory: "256Mi"
                  ephemeral-storage: 100Mi
                limits:
                  cpu: "200m"
                  memory: "256Mi"
                  ephemeral-storage: 100Mi
